-- Can Collector (cancollector) — Supabase schema
--
-- Canonical migration: supabase/migration.sql
-- Copy and run that file in the Supabase SQL Editor for new projects.
-- It includes profiles, cans, indexes, updated_at triggers, RLS, auth trigger,
-- and can-images storage policies.
